triple_important = [
    "vaccine",
    "drugs",
    "drug",
    "methanol",
    "temperature",
    "temperatures",
]

double_important = [
    "antibiotics",
    "droplets",
    "houseflies",
]

keys = {
    "covid-19": ["covid-19", "covid", "coronavirus", "covid19"],
    "drugs": ["drugs", "drug"],
    "meals": ["meals", "meal", "breakfast", "dinner"],
    "houseflies": ["houseflies", "housefly"],
    "coughs": ["coughs", "cough"],
    "sneezes": ["sneezes", "sneeze"],
    "speaks": ["speaks", "speak"],
    "does": ["does", "will"],
    "waves": ["waves", "wave"],
    "networks": ["networks", "network"],
    "spreading": ["spreading", "spreads", "spread"],
    "countries": ["countries", "country", "nations", "nation"],
    "droplets": ["droplets", "droplet"],
    "surface": ["surface", "surfaces"],
    "temperatures": ["temperatures", "temperature"],
    "recover": ["recovers", "recovering"],
    "bodies": ["bodies", "body"],
    "weather": ["weather", "climate"],
    "virus": ["viruses", "virus"],
    "Antibiotics": ["Antibiotics", "Antibiotic"],
    "scanners": ["scanners", "scanner"],
    "vaccine": ["vaccine", "vaccines"],
    "ages": ["ages", "age"],
}

facts = [
    "There are currently no drugs licensed for the treatment or prevention of COVID-19",
    "Adding pepper to your soup or other meals DOES NOT prevent or cure COVID-19",
    "COVID-19 IS NOT transmitted through houseflies",
    "The virus that cause COVID-19 spreads primarily through droplets generated when an infected person coughs, sneezes or speaks",
    "You can also become infected by touching a contaminated surface and then touching your eyes, nose or mouth before washing your hands",
    "Spraying and introducing bleach or another disinfectant into your body WILL NOT protect you against COVID-19 and can be dangerous",
    "Bleach and disinfectants can be poisonous if ingested and cause irritation and damage to your skin and eyes.",
    "Remember to keep chlorine (bleach) and other disinfectants out of reach of children",
    "Drinking methanol, ethanol or bleach DOES NOT prevent or cure COVID-19 and can be extremely dangerous",
    "Drinking methanol, ethanol or bleach can lead to disability and death",
    "Methanol, Ethanol or Bleach will not kill the virus in your body and they will harm your internal organs",
    "5G mobile networks DO NOT spread COVID-19",
    "Virus cannot travel on radio waves/mobile networks",
    "COVID-19 is spreading in many countries that do not have 5G mobile networks",
    "COVID-19 is spread through respiratory droplets when an infected person coughs, sneezes or speaks",
    "People can also be infected by touching a contaminated surface and then their eyes, mouth or nose",
    "Exposing yourself to the sun or to temperatures higher than 25C degrees DOES NOT prevent the coronavirus disease (COVID-19)",
    "You can catch COVID-19, no matter how sunny or hot the weather is",
    "Countries with hot weather have reported cases of COVID-19",
    "You can recover from the coronavirus disease (COVID-19)",
    "Catching the new coronavirus DOES NOT mean you will have it for life",
    "Most of the people who catch COVID-19 can recover and eliminate the virus from their bodies",
    "If you have cough, fever, and difficulty breathing, seek medical care early – but call your health facility by telephone first",
    "Being able to hold your breath for 10 seconds or more without coughing or feeling discomfort DOES NOT mean you are free from the coronavirus disease (COVID-19) or any other lung disease.",
    "The most common symptoms of COVID-19 are dry cough, tiredness and fever",
    "Some people with COVID-19 may develop more severe forms of the disease, such as pneumonia",
    "The best way to confirm if you have the virus producing COVID-19 disease is with a laboratory test",
    "You cannot confirm COVID-19 with this breathing exercise, which can even be dangerous",
    "Drinking alcohol does not protect you against COVID-19 and can be dangerous",
    "Frequent or excessive alcohol consumption can increase your risk of health problems",
    "COVID-19 virus can be transmitted in areas with hot and humid climates",
    "The best way to protect yourself against COVID-19 is by maintaining physical distance of at least 1 metre from others and frequently cleaning your hands",
    "Cold weather and snow CANNOT kill the new coronavirus",
    "There is no reason to believe that cold weather can kill the new coronavirus or other diseases",
    "Taking a hot bath will not prevent you from catching COVID-19",
    "Actually, taking a hot bath with extremely hot water can be harmful, as it can burn you and will not prevent you from catching COVID-19",
    "The new coronavirus CANNOT be transmitted through mosquito bites",
    "To date there has been no information nor evidence to suggest that the new coronavirus could be transmitted by mosquitoes",
    "The new coronavirus is a respiratory virus which spreads primarily through droplets generated when an infected person coughs or sneezes, or through droplets of saliva or discharge from the nose",
    "To protect yourself, clean your hands frequently with an alcohol-based hand rub or wash them with soap and water",
    "Avoid close contact with anyone who is coughing and sneezing",
    "Hand dryers are not effective in killing the coronavirus",
    "Ultra-violet (UV) lamps should not be used to disinfect hands or other areas of your skin",
    "UV radiation can cause skin irritation and damage your eyes",
    "Thermal scanners are effective in detecting people who have developed a fever because of infection with the new coronavirus.",
    "Thermal scanners cannot detect people who are infected with COVID-19 but are not yet sick with fever",
    "It takes between 2 and 10 days before people who are infected with COVID-19 become sick and develop a fever.",
    "Vaccine against pneumonia, such as pneumococcal vaccine and Haemophilus influenza type B (Hib) vaccine, do not provide protection against the new coronavirus",
    "The coronavirus is so new and different that it needs its own vaccine.",
    "There is no evidence that regularly rinsing the nose with saline has protected people from infection with the new coronavirus",
    "There is some limited evidence that regularly rinsing nose with saline can help people recover more quickly from the common cold but not coronavirus",
    "Garlic is a healthy food that may have some antimicrobial properties. However, there is no evidence from the current outbreak that eating garlic has protected people from the new coronavirus",
    "People of all ages can be infected by the new coronavirus",
    "Older people, and people with pre-existing medical conditions (such as asthma, diabetes, heart disease) appear to be more vulnerable to becoming severely ill with the virus",
    "WHO advises people of all ages to take steps to protect themselves from the virus, for example by following good hand hygiene and good respiratory hygiene",
    "Antibiotics do not work against virus, only bacteria.",
    "The new coronavirus ( COVID-19 ) is a virus and, therefore, antibiotics should not be used as a means of prevention or treatment",
    "If you are hospitalized for the COVID-19, you may receive antibiotics because bacterial co-infection is possible.",
]
